spring:
  application:
    name: kobeai-hub
  
  datasource:
    url: jdbc:mysql://39.98.107.158:3306/IntelliFlowAI?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kobe200800
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: KobeAIHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  redis:
    host: 39.98.107.158
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  # RabbitMQ配置
  rabbitmq:
    host: 39.98.107.158
    username: wangliang
    password: kobe200800
    port: 5672

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 3130187893@qq.com
    password: temhyrznlggedgff
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # 热部署配置
  devtools:
    restart:
      enabled: true # 开启热部署
      additional-paths: src/main/java # 重启目录
      exclude: WEB-INF/** # 排除WEB-INF目录
    livereload:
      enabled: true # 开启livereload
      port: 35729 # livereload端口

  websocket:
    enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: kobeai-jwt-secret-key-must-be-at-least-256-bits-long-for-security
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    root: INFO
    com.kobeai.hub: DEBUG
  file:
    name: logs/kobeai-hub.log

knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
    enable-footer: false
    enable-footer-custom: false
  basic:
    enable: false
  production: false

springfox:
  documentation:
    swagger-ui:
      enabled: true

cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

app:
  upload:
    dir: uploads

# MinIO Configuration
minio:
  endpoint: http://39.98.107.158:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: photo
